apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    type: nfs
spec:
  storageClassName: efs-sc
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-087fd49e4e6612df0