apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ template "jenkins.fullname" . }}
  replicas: {{ .Values.replicas | default 1 }}
  strategy:
{{- toYaml .Values.strategy | nindent 4 }}
  template:
    metadata:
      labels:
        app: {{ template "jenkins.fullname" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
      - name: jenkins
        image: {{ .Values.jenkinsImage | default "jenkins/jenkins:2.401.3-lts-alpine" }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "IfNotPresent" }}
        {{- if .Values.javaOpts }}
        env:
        - name: JAVA_OPTS
          value: "{{ .Values.javaOpts }}"
        {{- end }}
        ports:
        - name: httpport
          containerPort: {{ .Values.service.httpPort | default 8080 }}
        - name: jnlpport
          containerPort: {{ .Values.service.jnlpPort | default 50000 }}
        livenessProbe: 
     {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe: 
     {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources: 
     {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - mountPath: {{ .Values.volumeMountPath }}
          name: jenkins
      securityContext:
        runAsUser: 0
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
      - name: jenkins
        # emptyDir: {}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaimName }}
