apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
  labels:
    app: {{ template "jenkins.fullname" . }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '{{ .Values.service.httpPort }}'
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      protocol: TCP
    - name: slave
      port: {{ .Values.service.jnlpPort }}
      protocol: TCP
    - name: http
      port: 80
      targetPort: {{ .Values.service.httpPort }}
  selector:
    app: {{ template "jenkins.fullname" . }}