replicas: 1
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

fullnameOverride: jenkins-chart

serviceAccountName: jenkins-sa
clusterRoleName: jenkins-role

jenkinsImage: jenkins/jenkins:2.401.3-lts-alpine
imagePullPolicy: IfNotPresent
javaOpts: "-Xmx2048m -Dhudson.slaves.NodeProvisioner.MARGIN=50 -Dhudson.slaves.NodeProvisioner.MARGIN0=0.85"

service:
  httpPort: 8080
  jnlpPort: 50000

livenessProbe:
  httpGet:
    path: "/login"
    port: httpport
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: "/login"
    port: httpport
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

volumeMountPath: /var/jenkins_home


terminationGracePeriodSeconds: 30

resources:
  requests:
    cpu: "500m"
    memory: "500Mi"
  limits:
    cpu: "1000m"
    memory: "2Gi"


persistence:
  enabled: true 
  volumeName: jenkins
  volumeClaimName: "jenkins-claim"
  type: local

  nfs:
    storageClassName: efs-sc
    capacity:
      storage: 5Gi
    volumeMode: Filesystem
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    csi:
      driver: efs.csi.aws.com
      volumeHandle: fs-087fd49e4e6612df0

  local:
    storageClassName: manual
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
      path: "/mnt/data"


  # # type: local
  # storageClass: efs-sc
  # # storageClass: manual

  # size: "5Gi"
  # volumeMode: Filesystem
  # # accessMode: ReadWriteOnce
  # accessMode: ReadWriteMany
  
  # csi:
  #   driver: efs.csi.aws.com
  #   volumeHandle: fs-087fd49e4e6612df0
  
  # persistentVolumeReclaimPolicy: Retain

